### ISSUE TITLE
Use of AMAZON.LITERAL for the name slot

### ISSUE THREAD

**Issue by deanobalino** [craigbilner/arithlistic#1]
Hi Craig, 

Great write up and skill! I was taking a look at your intent schema and had some feedback.

Below in quotes are the amazon guidelines on using the AMAZON.LITERAL slot type. From the docs here: https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/defining-the-voice-interface

I would recommend using AMAZON.US_FIRST_NAME and then if you really need surnames, maybe a second custom slot for their second name. Remember, you can always add your own values to the built-in slots too. Details here: https://developer.amazon.com/appsandservices/community/post/Tx3Q9SLKOW69DJ0/New-ASK-Features-Extensible-Built-In-Types

'An additional built-in slot type is supported: AMAZON.LITERAL. The AMAZON.LITERAL type is maintained primarily for backwards compatibility with skills produced by earlier versions of the Alexa Skills Kit and is not recommended for most use cases going forward. Normally you should use a custom slot type rather than AMAZON.LITERAL.'

**Comment by craigbilner** [comment]
Thanks @deanobalino, yeah I was a bit naughty, should have put that as a todo, fixed now. #2
